Internal Server Error: /trigger-error/
Traceback (most recent call last):
  File "/Users/arnavshah/Documents/mafiawebsite/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arnavshah/Documents/mafiawebsite/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arnavshah/Documents/mafiawebsite/myapp/views.py", line 486, in trigger_error
    1/0
    ~^~
ZeroDivisionError: division by zero
"GET /trigger-error/ HTTP/1.1" 500 8653
Internal Server Error: /trigger-error/
Traceback (most recent call last):
  File "/Users/arnavshah/Documents/mafiawebsite/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arnavshah/Documents/mafiawebsite/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arnavshah/Documents/mafiawebsite/myapp/views.py", line 486, in trigger_error
    1/0
    ~^~
ZeroDivisionError: division by zero
"GET /trigger-error/ HTTP/1.1" 500 8653
Internal Server Error: /trigger-error/
Traceback (most recent call last):
  File "/Users/arnavshah/Documents/mafiawebsite/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arnavshah/Documents/mafiawebsite/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arnavshah/Documents/mafiawebsite/myapp/views.py", line 486, in trigger_error
    1/0
    ~^~
ZeroDivisionError: division by zero
"GET /trigger-error/ HTTP/1.1" 500 8653
